 /*==========================================================================
                SeqAn - The Library for Sequence Analysis
                          http://www.seqan.de 
 ============================================================================
  Copyright (C) 2007

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 3 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

 ==========================================================================*/

#ifndef SEQAN_HEADER_CONSENSUS_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_CONSENSUS_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// Bayesian_

struct Bayesian_;       	// "projects/library/seqan/consensus/consensus_base.h"(65)

//____________________________________________________________________________
// ConsensusOptions

struct ConsensusOptions;       	// "projects/library/seqan/consensus/consensus_base.h"(77)

//____________________________________________________________________________
// ConsensusScore_

struct ConsensusScore_;       	// "projects/library/seqan/consensus/consensus_score.h"(35)

//____________________________________________________________________________
// FractionalScore_

struct FractionalScore_;       	// "projects/library/seqan/consensus/consensus_score.h"(40)

//____________________________________________________________________________
// Majority_Vote_

struct Majority_Vote_;       	// "projects/library/seqan/consensus/consensus_base.h"(57)

//____________________________________________________________________________
// Overlap_Library_

struct Overlap_Library_;       	// "projects/library/seqan/consensus/consensus_base.h"(37)

//____________________________________________________________________________
// ProfileType

template <typename TValue, typename TCount , typename TSpec > class ProfileType;       	// "projects/library/seqan/consensus/consensus_profile.h"(31)
template <typename TValue, typename TCount, typename TSpec> class ProfileType;       	// "projects/library/seqan/consensus/consensus_profile.h"(35)

//____________________________________________________________________________
// WeightedConsensusScore

template <typename TScore1, typename TScore2> struct WeightedConsensusScore;       	// "projects/library/seqan/consensus/consensus_score.h"(46)

//____________________________________________________________________________
// _LessPair

template <typename TSize> struct _LessPair;       	// "projects/library/seqan/consensus/consensus_library.h"(82)

//____________________________________________________________________________
// _LessTripel

template <typename TSize> struct _LessTripel;       	// "projects/library/seqan/consensus/consensus_library.h"(93)

} //namespace SEQAN_NAMESPACE_MAIN


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// Bayesian

typedef Tag<Bayesian_> const Bayesian;       	// "projects/library/seqan/consensus/consensus_base.h"(66)

//____________________________________________________________________________
// ConsensusScore

typedef Tag<ConsensusScore_> const ConsensusScore;       	// "projects/library/seqan/consensus/consensus_score.h"(36)

//____________________________________________________________________________
// FractionalScore

typedef Tag<FractionalScore_> const FractionalScore;       	// "projects/library/seqan/consensus/consensus_score.h"(41)

//____________________________________________________________________________
// Majority_Vote

typedef Tag<Majority_Vote_> const Majority_Vote;       	// "projects/library/seqan/consensus/consensus_base.h"(58)

//____________________________________________________________________________
// Overlap_Library

typedef Tag<Overlap_Library_> const Overlap_Library;       	// "projects/library/seqan/consensus/consensus_base.h"(38)

} //namespace SEQAN_NAMESPACE_MAIN


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// __countLetters

template <typename TValue, typename TSpec, typename TCounters, typename TCoverage, typename TSize, typename TAlphabet> inline void __countLetters(String<TValue, TSpec> const& mat, TCounters& counterValues, TCoverage& coverage, TSize alignDepth, TAlphabet);       	// "projects/library/seqan/consensus/consensus_base.h"(543)

//____________________________________________________________________________
// __getAlignmentStatistics

template <typename TSize> inline void __getAlignmentStatistics(Nothing&, TSize, TSize, TSize, double, double);       	// "projects/library/seqan/consensus/consensus_library.h"(37)
template <typename TValue, typename TSpec, typename TSize> inline void __getAlignmentStatistics(String<TValue, TSpec>& dist, TSize i, TSize j, TSize nseq, double matchLen, double quality);       	// "projects/library/seqan/consensus/consensus_library.h"(51)
template <typename TCargo, typename TSpec, typename TSize> inline void __getAlignmentStatistics(Graph<Undirected<TCargo, TSpec> >& dist, TSize i, TSize j, TSize, double matchLen, double quality);       	// "projects/library/seqan/consensus/consensus_library.h"(68)

//____________________________________________________________________________
// _getMaxIndex

template <typename TSourceValue, typename TSourceCount, typename TSourceSpec> inline typename Size<ProfileType<TSourceValue, TSourceCount, TSourceSpec> const >::Type _getMaxIndex(ProfileType<TSourceValue, TSourceCount, TSourceSpec> const & source);       	// "projects/library/seqan/consensus/consensus_profile.h"(133)

//____________________________________________________________________________
// _loadContigReads

template <typename TValue, typename TStrSpec, typename TPosPair, typename TStringSpec, typename TSpec, typename TConfig, typename TId> inline void _loadContigReads(StringSet<TValue, Owner<TStrSpec> >& strSet, String<TPosPair, TStringSpec>& startEndPos, FragmentStore<TSpec, TConfig> const& fragStore, TId const contigId);       	// "projects/library/seqan/consensus/consensus_base.h"(148)

//____________________________________________________________________________
// appendSegmentMatches

template <typename TString, typename TSpec, typename TId, typename TDiagList, typename TBegEndPos, typename TScore, typename TSize, typename TSegmentMatches, typename TScoreValues, typename TDistance> inline void appendSegmentMatches(StringSet<TString, TSpec> const& str, String<Pair<TId, TId> > const& pList, TDiagList const& dList, TBegEndPos const& begEndPos, TScore const& score_type, TSize thresholdMatchlength, TSize thresholdQuality, TSize maxOvl, TSegmentMatches& matches, TScoreValues& scores, TDistance& dist, Overlap_Library);       	// "projects/library/seqan/consensus/consensus_library.h"(409)

//____________________________________________________________________________
// assign

template <typename TTargetValue, typename TTargetSpec, typename TSourceValue, typename TSourceCount, typename TSourceSpec> inline void assign(SimpleType<TTargetValue, TTargetSpec> & target, ProfileType<TSourceValue, TSourceCount, TSourceSpec> const & source);       	// "projects/library/seqan/consensus/consensus_profile.h"(154)

//____________________________________________________________________________
// assignProfile

template <typename TValue, typename TString> inline void assignProfile(Score<TValue, ConsensusScore>& me, TString const& profile);       	// "projects/library/seqan/consensus/consensus_score.h"(82)
template <typename TValue, typename TString> inline void assignProfile(Score<TValue, FractionalScore>& me, TString const& profile);       	// "projects/library/seqan/consensus/consensus_score.h"(194)
template <typename TValue, typename TScore1, typename TScore2, typename TString> inline void assignProfile(Score<TValue, WeightedConsensusScore<TScore1, TScore2> >& me, TString const& profile);       	// "projects/library/seqan/consensus/consensus_score.h"(300)

//____________________________________________________________________________
// consensusAlignment

template <typename TStringSet, typename TCargo, typename TSpec, typename TSize, typename TConfigOptions> inline void consensusAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& gOut, String<Pair<TSize, TSize> >& begEndPos, TConfigOptions const& consOpt);       	// "projects/library/seqan/consensus/consensus_base.h"(193)
template <typename TStringSet, typename TCargo, typename TSpec, typename TSize> inline void consensusAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& gOut, String<Pair<TSize, TSize> >& begEndPos);       	// "projects/library/seqan/consensus/consensus_base.h"(269)

//____________________________________________________________________________
// consensusCalling

template <typename TValue, typename TSpec, typename TAlphabet, typename TSpec2, typename TGappedConsensus, typename TCoverage, typename TSize> inline void consensusCalling(String<TValue, TSpec> const& mat, String<TAlphabet, TSpec2>& consensus, TGappedConsensus& gappedConsensus, TCoverage& coverage, TSize alignDepth, Bayesian);       	// "projects/library/seqan/consensus/consensus_base.h"(600)
template <typename TValue, typename TSpec, typename TAlphabet, typename TSpec2, typename TGappedConsensus, typename TCoverage, typename TSize> inline void consensusCalling(String<TValue, TSpec> const& mat, String<TAlphabet, TSpec2>& consensus, TGappedConsensus& gappedConsensus, TCoverage& coverage, TSize alignDepth, Majority_Vote);       	// "projects/library/seqan/consensus/consensus_base.h"(985)

//____________________________________________________________________________
// convertImpl

template <typename TTarget, typename T, typename TSourceValue, typename TSourceCount, typename TSourceSpec> inline typename Convert<TTarget, ProfileType<TSourceValue, TSourceCount, TSourceSpec> >::Type convertImpl(Convert<TTarget, T> const, ProfileType<TSourceValue, TSourceCount, TSourceSpec> const & source);       	// "projects/library/seqan/consensus/consensus_profile.h"(164)

//____________________________________________________________________________
// empty

template <typename TSourceValue, typename TSourceCount, typename TSourceSpec> inline bool empty(ProfileType<TSourceValue, TSourceCount, TSourceSpec> const & source);       	// "projects/library/seqan/consensus/consensus_profile.h"(119)

//____________________________________________________________________________
// fixDisruptedReads

template <typename TValue, typename TSpec, typename TStringSet, typename TScore, typename TBegEndRow, typename TSize> inline TSize fixDisruptedReads(String<TValue, TSpec>& mat, TStringSet const& str, TScore& scType, TBegEndRow& begER, TSize alignDepth);       	// "projects/library/seqan/consensus/consensus_base.h"(845)

//____________________________________________________________________________
// insertGap

template <typename TPos, typename TGapAnchor, typename TSpec, typename TGapPos> inline int insertGap(AlignedReadStoreElement<TPos, TGapAnchor, TSpec>& alignedRead, TGapPos const gapPos);       	// "projects/library/seqan/consensus/consensus_realign.h"(70)
template <typename TAlignedReads, typename TSpec, typename TGapPos> inline int insertGap(String<TAlignedReads, TSpec>& alignedReadStore, TGapPos const gapPos);       	// "projects/library/seqan/consensus/consensus_realign.h"(130)

//____________________________________________________________________________
// operator<<

template <typename TStream, typename TValue, typename TCount, typename TSpec> inline TStream& operator<<(TStream& os, ProfileType<TValue, TCount, TSpec> const& rhs);       	// "projects/library/seqan/consensus/consensus_profile.h"(172)

//____________________________________________________________________________
// reAlign

template <typename TFragSpec, typename TConfig, typename TAlignedRead, typename TSpec, typename TConsensus, typename TScore, typename TMethod, typename TBandwidth> inline void reAlign(FragmentStore<TFragSpec, TConfig>& fragStore, String<TAlignedRead, TSpec>& contigReads, TConsensus& consensus, TScore& consScore, TMethod const rmethod, TBandwidth const bandwidth, bool includeReference);       	// "projects/library/seqan/consensus/consensus_realign.h"(182)
template <typename TSpec, typename TConfig, typename TScore, typename TId, typename TMethod, typename TBandwidth> inline void reAlign(FragmentStore<TSpec, TConfig>& fragStore, TScore& consScore, TId const contigId, TMethod const rmethod, TBandwidth const bandwidth, bool includeReference);       	// "projects/library/seqan/consensus/consensus_realign.h"(483)
template <typename TSpec, typename TConfig, typename TScore, typename TId, typename TBandwidth> inline void reAlign(FragmentStore<TSpec, TConfig>& fragStore, TScore& consScore, TId const contigId, TBandwidth const bandwidth, bool includeReference);       	// "projects/library/seqan/consensus/consensus_realign.h"(676)

//____________________________________________________________________________
// realignLowQualityReads

template <typename TStringSet, typename TCargo, typename TSpec, typename TBegEndRowPos, typename TNewLibraryGraph> inline unsigned int realignLowQualityReads(Graph<Alignment<TStringSet, TCargo, TSpec> > const& gIn, TBegEndRowPos const& readBegEndRowPos, TNewLibraryGraph& gOut);       	// "projects/library/seqan/consensus/consensus_base.h"(1028)

//____________________________________________________________________________
// removeGap

template <typename TPos, typename TGapAnchor, typename TSpec, typename TGapPos> inline void removeGap(AlignedReadStoreElement<TPos, TGapAnchor, TSpec>& alignedRead, TGapPos const gapPos);       	// "projects/library/seqan/consensus/consensus_realign.h"(33)
template <typename TAlignedReads, typename TSpec, typename TGapPos> inline void removeGap(String<TAlignedReads, TSpec>& alignedReadStore, TGapPos const gapPos);       	// "projects/library/seqan/consensus/consensus_realign.h"(54)

//____________________________________________________________________________
// score

template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue score(Score<TValue, ConsensusScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &, TSeq2 const &seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(160)
template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue score(Score<TValue, FractionalScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(265)
template <typename TValue, typename TScore1, typename TScore2, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue score(Score<TValue, WeightedConsensusScore<TScore1, TScore2> > const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(364)

//____________________________________________________________________________
// scoreConsensus

template <typename TConsensus> inline int scoreConsensus(TConsensus& consensus);       	// "projects/library/seqan/consensus/consensus_realign.h"(147)

//____________________________________________________________________________
// scoreGapExtendHorizontal

template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendHorizontal( Score<TValue, ConsensusScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(111)
template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendHorizontal( Score<TValue, FractionalScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(218)
template <typename TValue, typename TScore1, typename TScore2, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendHorizontal( Score<TValue, WeightedConsensusScore<TScore1, TScore2> > const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(315)

//____________________________________________________________________________
// scoreGapExtendVertical

template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendVertical( Score<TValue, ConsensusScore> const &, TPos1, TPos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(136)
template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendVertical( Score<TValue, FractionalScore> const &, TPos1, TPos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(242)
template <typename TValue, typename TScore1, typename TScore2, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapExtendVertical( Score<TValue, WeightedConsensusScore<TScore1, TScore2> > const & me, TPos1 pos1, TPos2 pos2, TSeq1 const & seq1, TSeq2 const & seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(340)

//____________________________________________________________________________
// scoreGapOpenHorizontal

template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenHorizontal( Score<TValue, ConsensusScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(123)
template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenHorizontal( Score<TValue, FractionalScore> const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(230)
template <typename TValue, typename TScore1, typename TScore2, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenHorizontal( Score<TValue, WeightedConsensusScore<TScore1, TScore2> > const & me, TPos1 pos1, TPos2 pos2, TSeq1 const &seq1, TSeq2 const &seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(327)

//____________________________________________________________________________
// scoreGapOpenVertical

template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenVertical( Score<TValue, ConsensusScore> const &, TPos1, TPos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(148)
template <typename TValue, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenVertical( Score<TValue, FractionalScore> const &, TPos1, TPos2, TSeq1 const &, TSeq2 const &);       	// "projects/library/seqan/consensus/consensus_score.h"(254)
template <typename TValue, typename TScore1, typename TScore2, typename TPos1, typename TPos2, typename TSeq1, typename TSeq2> inline TValue scoreGapOpenVertical( Score<TValue, WeightedConsensusScore<TScore1, TScore2> > const & me, TPos1 pos1, TPos2 pos2, TSeq1 const & seq1, TSeq2 const & seq2);       	// "projects/library/seqan/consensus/consensus_score.h"(352)

//____________________________________________________________________________
// selectPairs

template <typename TString, typename TSpec, typename TBegEndPos, typename TSize, typename TPairList, typename TPos, typename TSpec2> inline void selectPairs(StringSet<TString, TSpec> const& str, TBegEndPos const& begEndPos, TSize bandwidth, TPairList& pList, String<Pair<TPos, TPos>, TSpec2>& dList);       	// "projects/library/seqan/consensus/consensus_library.h"(110)

//____________________________________________________________________________
// selectPairsIndel

template <typename TString, typename TSpec, typename TBegEndPos, typename TSize, typename TPairList, typename TPos, typename TSpec2> inline void selectPairsIndel(StringSet<TString, TSpec> const& str, TBegEndPos const& begEndPos, TSize lookAround, TPairList& pList, String<Pair<TPos, TPos>, TSpec2>& dList);       	// "projects/library/seqan/consensus/consensus_library.h"(348)

//____________________________________________________________________________
// updateContig

template <typename TFragSpec, typename TConfig, typename TStringSet, typename TCargo, typename TSpec, typename TContigId> inline void updateContig(FragmentStore<TFragSpec, TConfig>& fragStore, Graph<Alignment<TStringSet, TCargo, TSpec> > const& g, TContigId contigId);       	// "projects/library/seqan/consensus/consensus_base.h"(282)

} //namespace SEQAN_NAMESPACE_MAIN

#endif

